// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CalcTimeAllCpp
NumericVector CalcTimeAllCpp(NumericVector ID, NumericVector Abs_dates, NumericVector Rating, NumericVector labels, double end_date);
RcppExport SEXP transprob_CalcTimeAllCpp(SEXP IDSEXP, SEXP Abs_datesSEXP, SEXP RatingSEXP, SEXP labelsSEXP, SEXP end_dateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ID(IDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Abs_dates(Abs_datesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rating(RatingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type end_date(end_dateSEXP);
    __result = Rcpp::wrap(CalcTimeAllCpp(ID, Abs_dates, Rating, labels, end_date));
    return __result;
END_RCPP
}
// CalcTimeObservedOnlyCpp
NumericVector CalcTimeObservedOnlyCpp(NumericVector ID, NumericVector Abs_dates, NumericVector Rating, NumericVector labels, double end_date);
RcppExport SEXP transprob_CalcTimeObservedOnlyCpp(SEXP IDSEXP, SEXP Abs_datesSEXP, SEXP RatingSEXP, SEXP labelsSEXP, SEXP end_dateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ID(IDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Abs_dates(Abs_datesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rating(RatingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type end_date(end_dateSEXP);
    __result = Rcpp::wrap(CalcTimeObservedOnlyCpp(ID, Abs_dates, Rating, labels, end_date));
    return __result;
END_RCPP
}
// CalcTransCpp
NumericMatrix CalcTransCpp(NumericVector ID, NumericVector Rating, NumericVector labels);
RcppExport SEXP transprob_CalcTransCpp(SEXP IDSEXP, SEXP RatingSEXP, SEXP labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ID(IDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rating(RatingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type labels(labelsSEXP);
    __result = Rcpp::wrap(CalcTransCpp(ID, Rating, labels));
    return __result;
END_RCPP
}
