# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#' 
#' @param x A single integer.
CalcTimeAllCpp <- function(ID, Abs_dates, Rating, labels, end_date) {
    .Call('transprob_CalcTimeAllCpp', PACKAGE = 'transprob', ID, Abs_dates, Rating, labels, end_date)
}

#' Multiply a number by two
#' 
#' @param x A single integer.
CalcTimeObservedOnlyCpp <- function(ID, Abs_dates, Rating, labels, end_date) {
    .Call('transprob_CalcTimeObservedOnlyCpp', PACKAGE = 'transprob', ID, Abs_dates, Rating, labels, end_date)
}

CalcTransCpp <- function(ID, Rating, labels) {
    .Call('transprob_CalcTransCpp', PACKAGE = 'transprob', ID, Rating, labels)
}

